### ISSUE TITLE
Use Ruff as linter and formatter

### ISSUE THREAD

**Issue by RafaelWO** [RafaelWO/unparallel#85]
## 🚀 Feature Request

Currently, this project uses mypy for type checks and black plus isort for code formatting. It would be great to add [ruff](https://github.com/astral-sh/ruff) as a linter and use its formatter to replace black + isort.

## 🔈 Motivation

Ruff is very fast and we can use one tool instead for linting and formatting.

## 🛰 Alternatives

Just add flake8. But ruff also implements those rules.

## 📎 Additional context

n/a

**Comment by amitsgh** [comment]
Hello @RafaelWO, I would like to contribute on this issue.

**Comment by RafaelWO** [comment]
@amitsgh Sure, I'm happy for any contributions :) Please read the [contribution guidelines](https://github.com/RafaelWO/unparallel/blob/main/CONTRIBUTING.md) before you start. Then fork the repo and you're good to go!

**Comment by RafaelWO** [comment]
@amitsgh as I did not see that you have started with this issue, I took over. I hope this is fine for you 🙂
